### ISSUE TITLE
Missed inputs?

### ISSUE THREAD

**Issue by npSpeakerBee** [bitfocus/companion-module-vdo-ninja#19]
heyo ! 

Just started using the vdo module today, and running into issue with controlling my mic with a single streamdeck button.

##Description
Trying to setup a mute/unmute button, with press/release being the unmute/mute buttons on vdo.ninja (a push-to-talk key) - though half of the time one of the inputs is just missed? Is this an API limit/throttle or something else? 

##Reproduce
Press actions - VDO_Ninja: Local: Mic Control - Unmute
Release actions - VDO_Ninja: Local: Mic Control - Mute

Press the button a couple of times, all of a sudden you will be unmuted when you should be muted.

##Expected Behaviour
mute when I release the key

**Comment by bryce-seifert** [comment]
How are you determining your muted state? Via button feedback on the stream deck, or by looking at the VDO ninja window?

I just fixed an issues with the feedback when muting/unmuting local sources, because if you were using the button feedback it was showing up incorrectly for non-guest sources https://github.com/bitfocus/companion-module-vdo-ninja/commit/88e8069c34295adf5de8af9d35b7a988e916f9a1

If you want to give this a try, it should be in the Companion beta by tomorrow. Let me know if you're still having issues after testing that.
